name: projtest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.21.6
  - scipy=1.7.3
  - pillow=7.2.0
  - neurokit2=0.1.5
  - opencv=4.1.2
  - numpy=1.21.6
  - pytorch=1.11.0
